import type { IconType } from "react-icons";
import {
  SiPython,
  SiApachespark,
  SiApacheairflow,
  SiApachekafka,
  SiApachenifi,
  SiHive,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiSnowflake,
  SiElasticsearch,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiGooglecloud,
  SiGooglebigquery,
  SiDatabricks,
  SiLooker,
  SiMetabase,
  SiGit,
} from "react-icons/si";
import { FaAws, FaMicrosoft, FaDatabase } from "react-icons/fa";
import { BsStars } from "react-icons/bs";
import type { SkillIcon } from "./data";

export const iconMap: Record<SkillIcon, IconType> = {
  python: SiPython,
  pyspark: SiApachespark,
  apachespark: SiApachespark,
  apacheairflow: SiApacheairflow,
  apachekafka: SiApachekafka,
  apachenifi: SiApachenifi,
  hive: SiHive,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  snowflake: SiSnowflake,
  elasticsearch: SiElasticsearch,
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: SiReact,
  nextdotjs: SiNextdotjs,
  googlecloud: SiGooglecloud,
  googlebigquery: SiGooglebigquery,
  aws: FaAws,
  azure: FaMicrosoft,
  oracle: FaDatabase,
  databricks: SiDatabricks,
  looker: SiLooker,
  metabase: SiMetabase,
  git: SiGit,
  vertexai: BsStars,
  sql: FaDatabase,
};
