import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Dropdown from "../components/dropdown";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.scss";
import PictureOfMe from "../../public/images/[removal.ai]_tmp-61fbef991960f.png";
import site1 from "../../public/images/site1.png";
import site2 from "../../public/images/site2.png";
import site3 from "../../public/images/site3.png";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
  };

  useEffect(() => {
    const hideMenu = () => {
      if (window.innerWidth > 768 && isOpen) {
        setIsOpen(false);
      }
    };

    window.addEventListener("resize", hideMenu);

    return () => {
      window.removeEventListener("resize", hideMenu);
    };
  });
  return (
    <>
      <Head>
        <title>Oliveira Dev Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <body className={styles.body}>
          <Navbar toggle={toggle} />
          <Dropdown isOpen={isOpen} toggle={toggle} />
          <div className={styles.mainDiv}>
            <div className={styles.section1}>
              <h1>
                <span>Hello there 👋</span>
              </h1>
              <h2>This is my personal website.</h2>
              <h2>
                Here you can learn more about me, check some of my professional
                work and get in touch.
              </h2>
            </div>
            <div className={styles.section2}>
              <div className={styles.textContent}>
                <h3>About me</h3>
                <p>
                  Hi, my name is Caio Oliveira, I am 21 years old and a Computer
                  Engineering degree student at Universidade Federal de Goiás
                  (Goiania, GO - Brazil). I have been learning front-end
                  development for the last 2 years now and I also want to become
                  a Full Stack devolper in the future. My current favorite
                  development stack is NextJS - TypeScript - Sass or Tailwind.{" "}
                  <br />
                  <br />
                  As of my personal hobbies, I love reading comics (my favorite
                  character is Dr. Doom from Marvel), watch sports and learn new
                  things every single day.
                  <br />
                  <br />
                  Currently working at Kampana Digital but I am open to new
                  oportunities and challenges.
                </p>
              </div>
              <Image
                width="280"
                height="400"
                src={PictureOfMe}
                alt="Picture of me"
              />
            </div>
            <div className={styles.section3}>
              <h3>Projects</h3>
              <div className={styles.content3}>
                <div className={styles.Grid}>
                  <h4>Tutty Motors Website</h4>
                  <div className={styles.imageContainer}>
                    <Image width="900" height="450px" src={site1} alt="site1" />
                  </div>
                  <p>
                    My first professional website using <br /> Next, TS and
                    Sass.
                  </p>
                </div>
                <div className={styles.Grid}>
                  <h4>Zupot Landing Page</h4>
                  <div className={styles.imageContainer}>
                    <Image width="900" height="450px" src={site2} alt="site2" />
                  </div>
                  <p>
                    One of countless Landings Pages I have made <br /> at
                    Kampana.
                  </p>
                </div>
                <div className={styles.Grid}>
                  <h4>Tudaço Stores Page</h4>
                  <div className={styles.imageContainer}>
                    <Image width="900" height="450px" src={site3} alt="site3" />
                  </div>
                  <p>
                    Code maintenance in an e-commerce using <br />
                    HTML, CSS and JS.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </body>
      </main>
    </>
  );
};

export default Home;
